sudo: required
language: python
services:
  - docker
before_install:
  - docker pull tp33/django
  - docker pull mysql:latest
  - mkdir db
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/db:/var/lib/mysql  mysql:latest
  - docker exec -i mysql sleep 10&&mysql -uroot -p'$3cureUS' <<< "CREATE USER 'www'@'%' IDENTIFIED WITH mysql_native_password BY '$3cureUS';CREATE DATABASE cs4260;GRANT ALL ON cs4260.* to 'www'@'%';"
  - docker network create internet-scale-app_backend
  - docker network connect internet-scale-app_backend mysql
before_script:
  - docker-compose up
script:
  - docker exec -it selenium-test python test.py
after_script:
  - docker-compose stop
  - docker-compose rm y
  - rm -rf db