sudo: required
language: python
services:
  - docker
before_install:
  - docker pull mysql:5.7.28
  - mkdir db
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/db:/var/lib/mysql  mysql:5.7.28
  - sleep 20
  - docker exec -i mysql mysql -uroot -p'$3cureUS' <<< "drop user if exists 'www'@'%'; flush privileges; create user 'www'@'%' identified with mysql_native_password by '$3cureUS';grant all privileges on *.* to 'www'@'%' with grant option;"
  - docker network create internet-scale-app_backend
  - docker network connect internet-scale-app_backend mysql
before_script:
  - docker start mysql
  - docker-compose up
install:
  - pip install -r requirements.txt
script:
  - docker exec -it selenium-test python test.py
after_script:
  - docker-compose stop
  - docker-compose rm y
  - rm -rf db