version: "3"

services:
  entity:
    container_name: entity
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./entity:/app
    networks:
      - backend
      - services
    ports:
      - "8001:8000"
    command: bash -c "/app/init.sh"
  experience:
    container_name: experience
    image: tp33/django
    links:
      - entity
    volumes:
      - ./experience:/app
    networks:
      - services
      - public
    ports:
      - "8002:8000"
    command: bash -c "/app/init.sh"
  presentation_0:
    container_name: presentation-0
    image: tp33/django
    links: 
      - experience
    volumes:
      - ./presentation:/app
    networks: 
      - public
    ports:
      - "8003:8000"
    command: bash -c "/app/init.sh"
  presentation_1:
    container_name: presentation-1
    image: tp33/django
    links: 
      - experience
    volumes:
      - ./presentation:/app
    networks: 
      - public
    ports:
      - "8004:8000"
    command: bash -c "/app/init.sh"
  kafka:
    container_name: kafka
    image: spotify/kafka
    networks:
      - search
      - services
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    hostname: kafka
  batch:
    container_name: batch
    image: tp33/django
    volumes:
      - ./batch:/app
    networks:
      - search
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "8005:8000"
    command: bash -c "/app/init.sh"
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    networks:
      - services
      - search
    ports:
      - "9200:9200"
  selenium_chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    networks:
      - services
      - public
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  selenium_test:
    image: tp33/django
    container_name: selenium-test
    networks:
      - services
    volumes:
      - ./selenium:/app
    command: bash -c "/app/init.sh"
  load_balancer:
    image: haproxy
    container_name: load-balancer
    networks:
      - public
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8006:8000"
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - public
    ports:
      - "6379:6379"
  jmeter:
    image: justb4/jmeter
    container_name: jmeter
    networks:
        - public
    volumes:
      - ./jmeter:/etc
    command: -n -t /etc/test.jmx -l /etc/JmeterTestResult.log 
  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    container_name: spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./data:/tmp/data
  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 512m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data:/tmp/data

networks:
  backend:
    driver: bridge
  services:
    driver: bridge
  search:
    driver: bridge
  public: 
    driver: bridge