version: "3"
services:
  entity:
    container_name: entity
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./entity:/app
    networks:
      - backend
    ports:
      - "8001:8000"
    command: bash -c "/app/init.sh"
  experience:
    container_name: experience
    image: tp33/django
    links:
      - entity
    volumes:
      - ./experience:/app
    networks:
      - backend
    ports:
      - "8002:8000"
    command: bash -c "/app/init.sh"
  presentation:
    container_name: presentation
    image: tp33/django
    links: 
      - experience
    volumes:
      - ./presentation:/app
    ports:
      - "8003:8000"
    command: bash -c "/app/init.sh"
      
  
networks:
  backend:
    driver: bridge