version: "3"
services:
  models:
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./app:/app
    networks:
      - backend
    ports:
      - "8001:8000"
    command: bash -c "/app/init.sh"
  
networks:
  backend:
    driver: bridge