version: "3"

services:
  entity:
    container_name: entity
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./entity:/app
    networks:
      - backend
      - services
    ports:
      - "8001:8000"
    command: bash -c "/app/init.sh"
  experience:
    container_name: experience
    image: tp33/django
    links:
      - entity
    volumes:
      - ./experience:/app
    networks:
      - services
      - public
    ports:
      - "8002:8000"
    command: bash -c "/app/init.sh"
  presentation_0:
    container_name: presentation-0
    image: tp33/django
    links: 
      - experience
    volumes:
      - ./presentation:/app
    networks: 
      - public
    ports:
      - "8003:8000"
    command: bash -c "/app/init.sh"
  presentation_1:
    container_name: presentation-1
    image: tp33/django
    links: 
      - experience
    volumes:
      - ./presentation:/app
    networks: 
      - public
    ports:
      - "8004:8000"
    command: bash -c "/app/init.sh"
  kafka:
    container_name: kafka
    image: spotify/kafka
    networks:
      - search
      - services
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    hostname: kafka
  batch:
    container_name: batch
    image: tp33/django
    volumes:
      - ./batch:/app
    networks:
      - search
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "8005:8000"
    command: bash -c "/app/init.sh"
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    networks:
      - services
      - search
    ports:
      - "9200:9200"
  selenium_chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    networks:
      - services
      - public
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  selenium_test:
    image: tp33/django
    container_name: selenium-test
    networks:
      - services
    volumes:
      - ./selenium:/app
    command: bash -c "/app/init.sh"
  load_balancer:
    image: haproxy
    container_name: load-balancer
    networks:
      - public
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8006:8000"

networks:
  backend:
    driver: bridge
  services:
    driver: bridge
  search:
    driver: bridge
  public: 
    driver: bridge