version: "3"

services:
  entity:
    container_name: entity
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./entity:/app
    networks:
      - backend
      - services
    ports:
      - "8001:8000"
    command: bash -c "/app/init.sh"
  experience:
    container_name: experience
    image: tp33/django
    links:
      - entity
    volumes:
      - ./experience:/app
    networks:
      - services
      - public
    ports:
      - "8002:8000"
    command: bash -c "/app/init.sh"
  presentation:
    container_name: presentation
    image: tp33/django
    links: 
      - experience
    volumes:
      - ./presentation:/app
    networks: 
      - public
    ports:
      - "8003:8000"
    command: bash -c "/app/init.sh"
  kafka:
    container_name: kafka
    image: spotify/kafka
    networks:
      - search
      - services
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    hostname: kafka
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    networks:
      - services
      - search
    ports:
      - "9200:9200"
  batch:
    container_name: batch
    image: tp33/django
    volumes:
      - ./batch:/app
    networks:
      - search
networks:
  backend:
    driver: bridge
  services:
    driver: bridge
  search:
    driver: bridge
  public: 
    driver: bridge