version: "3"
services:
  models:
    container_name: web
    image: tp33/django
    external_links:
      - mysql:db
    volumes:
      - ./app:/app
    networks:
      - backend
    command: bash -c "/app/init.sh"
  experiences:
    container_name: data_services
    image: tp33/django
    links:
      - models
    volumes:
      - ./data-service:/app
    networks:
      - backend
    ports:
      - "8001:8000"
    command: bash -c "/app/setup.sh"
      
  
networks:
  backend:
    driver: bridge