# Generated by Django 2.2.4 on 2019-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191019_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('pet_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('co_views', models.TextField()),
            ],
        ),
    ]
